VERSION_YEAR = 2023
VERSION_MONTH = int('10')
VERSION_DAY = int('18')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('35')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202310180535
version_date = '2023/10/18 05:35'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
