VERSION_YEAR = 2023
VERSION_MONTH = int('11')
VERSION_DAY = int('21')
VERSION_HOUR = int('14')
VERSION_MINUTE = int('54')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202311211454
version_date = '2023/11/21 14:54'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
