VERSION_YEAR = 2023
VERSION_MONTH = int('08')
VERSION_DAY = int('29')
VERSION_HOUR = int('01')
VERSION_MINUTE = int('50')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202308290150
version_date = '2023/08/29 01:50'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
